Update BestpracticesTemplate.md
DISIC/foss-contrib-policy-template pull request #7
Opened 2016-12-15 03:17 UTC by jlovejoy

added language to specify inbound and outbound project license clearly

2016-12-15 16:12 UTC, gregkh commented on BestpracticesTemplate.md
> +* CONTRIBUTING: contributing guidelines, how to get involved, and identifiction of license or agreement under which contributions are accepted
identifiction?

2016-12-15 16:13 UTC, gregkh requested changes
spell check and I'll be glad to merge it :)

2016-12-16 21:03 UTC, jlovejoy commented
fixed now :)

2016-12-18 09:19 UTC, gregkh approved these changes
Thanks for making the change.

2016-12-18 09:19 UTC, merged